version: "3.7"

services:
  neo4j-db:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - /opt/data
      - /opt/plugins
    environment:
      - NEO4J_AUTH=neo4j/letmein
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
  service-api:
    build: .
    ports:
      - 4001:4001
    environment:
      - GRAPHQL_SERVER_HOST=0.0.0.0
      - GRAPHQL_SERVER_PATH=/graphql
      - GRAPHQL_SERVER_PORT=4001
      - NEO4J_URI=bolt://neo4j-db:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=letmein
      - NODE_ENV=development
    links:
      - neo4j-db
    depends_on:
      - neo4j-db
